package com.fanpower.lib.api.model

data class VerifyFanResponse(
    val avatar: String,
    val avatar_url: String,
    val birthday: Any,
    val created_at: String,
    val daily_sms_sent: Any,
    val email: Any,
    val encrypted_password: String,
    val first_name: String,
    val first_pick_sms_sent_at: String,
    val hometown: String,
    val id: String,
    val last_known_city: String,
    val last_known_state: String,
    val last_name: String,
    val lifetime_marketplace_pts: String,
    val marketplace_pts: String,
    val otp_secret_key: String,
    val persistence_token: String,
    val phone_code: String,
    val phone_number: String,
    val points: String,
    val points_reset_at: Any,
    val remember_created_at: Any,
    val reset_password_sent_at: Any,
    val reset_password_token: Any,
    val sms_policy_accepted_at: String,
    val time_zone: Any,
    val updated_at: String,
    val username: String,
    val welcome_sms_sent_at: String,
    val xfinity_fan: Any,
    val message : String
)